codecov:
  branch: dev
coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 2%
    patch:
      default:
        target: 60%
        threshold: 5%

comment: true
require_ci_to_pass: yes
